messenger/messenger/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls',namespace="myapp"))
]

messenger/myapp/urls.py
from django.urls import path
from . import views

app_name = "myapp"

urlpatterns = [
    path("", views.main_page, name = "main_page"),
    path("login", views.for_login, name = "for_login"),
    path("registration", views.for_registration, name = "for_registration"),
    path("userpage", views.user_page, name = "user_page"),
    path("log_out", views.log_out, name = "log_out"),
    path("add_post", views.adding_post, name = "adding_post"),
    path("<int:year>/<int:month>/<int:day>/<slug:slug>", views.find_post, name = "find_post"),
    path("<int:id>", views.shared, name="shared"),
    path("<int:id>/comment/",views.post_comment, name="post_comment"),
    path("tag",views.find_post_by_tag, name="find_by_tags")
]
 #path("send_email", views.send_email, name = "send_email")

messenger/myapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
# Create your models here.
class userPage(models.Model):
    '''class Status(models.TextChoices):
        ONLINE = ('ONLINE', 'Online')
        OFFLINE = ('OFFLINE', 'Offline')
    status = models.CharField(max_length = 7, choices = Status, default = Status.OFFLINE)'''
    OFFLINE = "OFF"
    ONLINE = "ON"
    CHOICES = [
        (OFFLINE, "Offline"),
        (ONLINE, "Online")
    ]
    status = models.CharField(max_length = 3, choices = CHOICES, default = OFFLINE)
    time = models.DateTimeField(default = timezone.now)
    user = models.OneToOneField(User, on_delete = models.CASCADE, default=None)

class Post(models.Model):
    tags = TaggableManager()
    body = models.CharField(max_length = 256, default = None)
    add_time = models.DateTimeField(default = timezone.now)
    user = models.ForeignKey(User,on_delete = models.CASCADE, default = None)
    title = models.CharField(max_length = 100)
    slug = models.SlugField(max_length = 250, default = None)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name = "comments")
    name = models.CharField(max_length = 80)
    email = models.EmailField()
    body = models.TextField()
    active = models.BooleanField(default = True)

    

messenger/myapp/forms.py
from django import forms
from myapp.models import Comment, Post
class Login(forms.Form):
    username = forms.CharField(widget = forms.TextInput(attrs={"placeholder":"Username"}))
    password = forms.CharField(widget = forms.PasswordInput(attrs={"placeholder":"password"}))

class Registration(forms.Form):
    username = forms.CharField(widget = forms.TextInput(attrs={"placeholder":"Username"}))
    email = forms.CharField(widget = forms.EmailInput(attrs={"placeholder":"email"}))
    password = forms.CharField(widget = forms.PasswordInput(attrs={"placeholder":"Password"}))

class add_new_post(forms.Form):
    title = forms.CharField(max_length = 100)
    body = forms.CharField(max_length = 256)
    slug = forms.SlugField(max_length = 250)

class find_form(forms.Form):
    day = forms.IntegerField(required=True)
    year = forms.IntegerField(required=True)
    month = forms.IntegerField(required=True)
    slug = forms.SlugField(max_length = 250,required=True)

'''class Email(forms.Form):

    email_from = forms.EmailField()
    email_to = forms.EmailField()
    text = forms.CharField(max_length = 256)'''
    
class Commentar(forms.ModelForm):
    class Meta():
        model = Comment
        #які поля потрібно використати із моделі
        fields = ['name', 'email', 'body']

class find_by_tags(forms.Form):
    tagg = forms.SlugField(max_length=80)

messenger/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.models import User
from myapp.models import userPage, Post, Comment
from django.utils import timezone
from myapp.forms import Login, Registration, add_new_post, find_form, Commentar, find_by_tags
from django.shortcuts import get_object_or_404
from taggit.models import Tag
#from django.core.mail import send_mail

def main_page(request):
    return render(request,"myapp/main_page.html")

def for_login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return HttpResponseRedirect(reverse("myapp:user_page"))
    return render(request,"myapp/logining.html",{
        "login_form":Login(),
    })

def for_registration(request):
    if request.method == "POST":
        form = Registration(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            if not User.objects.filter(username=username).exists() and not User.objects.filter(email=email).exists():
                new_user = User.objects.create_user(password=password,username=username,email=email)
                new_user.save()
                return HttpResponseRedirect(reverse("myapp:for_login"))
            else:
                return render(request,"myapp/regstration.html",{
                    "registration_form":Registration(),
                    "error":"User with the same email or username already exist!"
                })

    return render(request,"myapp/registration.html",{
        "registration_form":Registration(),
    })

def user_page(request):
    user_obj = userPage.objects.filter(user=request.user.id)[0]
    user_obj.status = "Online"
    user_obj.time = timezone.now()
    user_obj.save()
    if request.method == "POST":
        form = find_form(request.POST)
        if form.is_valid():
            year = form.cleaned_data['year']
            month = form.cleaned_data['month']
            day = form.cleaned_data['day']
            slug = form.cleaned_data['slug']
            print(year,month,day,slug)
            post = get_object_or_404(Post, 
                             add_time__year = year,
                             add_time__month = month,
                             add_time__day = day,
                             slug = slug
                             )
            return HttpResponseRedirect(reverse('myapp:find_post', args = (post.add_time.year,
                                                                           post.add_time.month,
                                                                           post.add_time.day,
                                                                           post.slug)))

    return render(request,"myapp/userpage.html",{
        "status":user_obj.status,
        "time":user_obj.time,
        "all_posts":Post.objects.filter(user=request.user.id),
        "find_form":find_form(),
        "tag_form":find_by_tags()
    })

def  log_out(request):
    user_obj = userPage.objects.filter(user=request.user.id)[0]
    user_obj.status = "Offline"
    user_obj.save()
    logout(request)
    return render(request,"myapp/main_page.html")

def adding_post(request):
    if request.method == "POST":
        form = add_new_post(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            body = form.cleaned_data['body']
            slug = form.cleaned_data['slug']
            obj = Post(title = title, body = body, slug = slug, add_time = timezone.now(), user = request.user)
            obj.save()
            return HttpResponseRedirect(reverse('myapp:user_page'))
    return render(request,'myapp/add_post.html',{
        "post_form":add_new_post(),
    })

def find_post(request, year, month, day, slug):
    post = get_object_or_404(Post, 
                             add_time__year = year,
                             add_time__month = month,
                             add_time__day = day,
                             slug = slug
                             )
    comments = post.comments.filter(active=True)
    return render(request,'myapp/post_which_finded.html',{
        "post":post,
        "comments":comments
    })

def shared(request, id):
    post = get_object_or_404(Post, id=id)
    return render(request, 'myapp/shared.html',{
        "post":post,
        "comment_form":Commentar(),
    })

def post_comment(request, id):
    post = get_object_or_404(Post, id=id)
    comment = None
    form = Commentar(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request,'myapp/shared.html',{
        "post":post,
        "comment_form":Commentar(),
        "comment":comment
    })

def find_post_by_tag(request):
    tag = None
    posts = None
    tag_slug = request.POST['tagg']
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = Post.objects.filter(tags__in=[tag])
    
    return render(request,'myapp/for_tag_finder.html',{
        "tag":tag,
        "posts":posts
    })

        








'''def send_email(request):
    sent = False
    if request.method == "POST":
        form = Email(request.POST,initial={'email_from': request.user.email})
        if form.is_valid():
            email_from = form.cleaned_data['email_from']
            email_to = form.cleaned_data['email_to']
            text = form.cleaned_data['text']
            send_mail('email form django', text, email_from, [email_to])
            sent = True
            return HttpResponseRedirect(reverse("myapp:user_page"))
    return render(request,'myapp/send_email.html',{
        "email_form":Email(),
        "sent":sent,
    })'''

messenger/myapp/templates/myapp/add_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add post</title>
</head>
<body>
    <form action="{% url 'myapp:adding_post' %}" method="post">
        {% csrf_token %}
        {{post_form}}
        <input type="submit" value="Add new post">
    </form>
    <a href="{% url 'myapp:user_page' %}">Return to your page</a>



</body>
</html>

messenger/myapp/templates/myapp/for_tag_finder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Find by Tag</title>
</head>
<body>
    <a href="{% url 'myapp:user_page' %}">Back</a>
    <p>Founded by tag : {{tag}}</p>
    <div>
        {% if posts %}
            {% for i in posts %}
                <div>
                    <h2>{{i.title}}</h2>
                    <p>{{i.body}}</p>
                    <h4>{{i.slug}}</h4>
                    <h3>{{i.add_time}}</h3>
                    <p>Tags : {{i.tags.all|join:", "}}</p>
                    <a href="{% url 'myapp:shared' i.id %}">Shared this post</a>
                    <hr>

                </div>
            {% endfor %}
        {% endif %}
    </div>
</body>
</html>

messenger/myapp/templates/myapp/logining.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login in page</title>
</head>
<body>
    <form action="{% url 'myapp:for_login' %}" method="post">
        {{login_form.as_p}}
        {% csrf_token %}
        <input type="submit" value="Log in">
    </form>
    <a href="{% url 'myapp:main_page' %}">Main page</a>
</body>
</html>

messenger/myapp/templates/myapp/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main messger page</title>
</head>
<body>
    <nav>
        <h1>Welcome to messenger</h1>
        <div><a href="{% url 'myapp:for_login' %}">Log in</a>
            <a href="{% url 'myapp:for_registration' %}">Registartion</a>
        </div>
    </nav>
    
    
</body>
</html>

messenger/myapp/templates/myapp/post_which_finded.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post</title>
</head>
<body>
    <div>
        <h2>{{post.title}}</h2>
        <p>{{post.body}}</p>
        <h4>{{post.slug}}</h4>
        <hr>
    </div>
    <div>
        {% for i in comments %}
            <p>{{i.name}}</p>
            <p>{{i.email}}</p>
            <p>{{i.body}}</p>
        {% endfor %}
    </div>
    <a href="{% url 'myapp:user_page' %}">Return on your page</a>
</body>
</html>

messenger/myapp/templates/myapp/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration page</title>
</head>
<body>
    <form action="{% url 'myapp:for_registration' %}" method="post">
        {% csrf_token %}
        {{registration_form.as_p}}
        <input type="submit" value="Registration">
        <div>
            {% if error %}
            <h1>{{error}}</h1>
            {% endif %}
        </div>
    </form>
    <a href="{% url 'myapp:main_page' %}">Main page</a>
</body>
</html>

messenger/myapp/templates/myapp/send_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Send email</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{email_form}}
        <input type="submit" value="Send">
    </form>
    <a href="{% url 'myapp:user_page' %}">Back to your page</a>
</body>
</html>

messenger/myapp/templates/myapp/shared.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shared Post</title>
    <style>
        div{
            border:1px solid black;
            padding:20px;
        }
    </style>
</head>
<body>
    <div>
        <h2>{{post.title}}</h2>
        <p>{{post.body}}</p>
        <h4>{{post.slug}}</h4>
    </div>
    <a href="{% url 'myapp:user_page' %}">Back</a>
    <form action="{% url 'myapp:post_comment' post.id%}" method="post">
        {% csrf_token %}
        {{comment_form.as_p}}
        <input type="submit" value="Add comment">
    </form>
    {% if comment %}
            <p>{{comment.name}}</p>
            <p>{{comment.email}}</p>
            <p>{{comment.body}}</p> 
    {% endif %}
</body>
</html>

messenger/myapp/templates/myapp/userpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Page</title>
    <style>
        #invisible{
            display:none;
            position:absolute;
            top:10%;
            left:80%;
            border:1px solid black;
            width:200px;
            height:200px;
        }
    </style>
</head>
<body>
    <div>
        <div>Time : {{time}}</div>
        <div>Status :{{status}}</div>
    </div>
    <div>
        <h3>My username : {{request.user.username}}</h3>
        <h3>My email : {{request.user.email}}</h3>
    </div>
    <a href="{% url 'myapp:log_out' %}">Log out</a>
    <a href="{% url 'myapp:adding_post' %}">Add new post</a>
    <hr>
    <div>
        {% if all_posts %}
            {% for i in all_posts %}
                <div>
                    <h2>{{i.title}}</h2>
                    <p>{{i.body}}</p>
                    <h4>{{i.slug}}</h4>
                    <h3>{{i.add_time}}</h3>
                    <p>Tags : {{i.tags.all|join:", "}}</p>
                    <a href="{% url 'myapp:shared' i.id %}">Shared this post</a>
                    <hr>

                </div>
            {% endfor %}
        {% endif %}
    </div>
    <div>
        <p>Find post :</p>
        <button id="for_form">Time and slug</button>
        <button id="for_slug">Tag</button>
    </div>
    <div id="invisible">
        <form action="{% url 'myapp:user_page' %}" method="post">
            {% csrf_token %}
            {{find_form}}
            <input type="submit" value="Find">
        </form>
    </div>
    <div id="invisible">
        <form action="{% url 'myapp:find_by_tags' %}" method="post">
            {% csrf_token %}
            {{tag_form}}
            <input type="submit" value="Find">
        </form>
    </div>
    <script>
        let for_form = document.querySelector('#for_form');
        let for_slug = document.querySelector('#for_slug');
        let invisible = document.querySelectorAll('#invisible');
        console.log(invisible);
        for_form.onclick = function(){
            invisible[0].style.display = "block";
            invisible[1].style.display = "none";
        }
        for_slug.onclick = function(){
            invisible[1].style.display = "block";
            invisible[0].style.display = "none";
        }

    </script>
</body>
</html>